M48
; DRILL file {KiCad 7.0.8} date Wed Jan 31 02:27:31 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-31T02:27:31-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.500
%
G90
G05
T1
X7.0Y26.0
X7.0Y20.22
T2
X3.0Y3.0
X67.0Y52.0
X67.0Y3.0
T3
X7.1Y50.13
T0
M30
